version: '3'

services:
  front:
    build: ./diario
    ports:
      - "3000:3000"
  
  back:
    build: ./mvc-go
    ports:
      - "8080:8080"
    environment:
      DB_HOST: "104.154.18.138"
      DB_PASS: "root"
      DB_USER: "root"
      DB_NAME: "diario"
      DB_PORT: "3306"
