version: '3'

services:
  front:
    build: ./diario
    ports:
      - "3000:3000"
  back:
    build: ./mvc-go
    restart: on-failure
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8080:8080"

  database:
    build: ./db
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: diario
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root","-p root"]
      timeout: 20s
      retries: 10