name: Build and Publish
on:
  push:
    branches:
      - main
jobs:

  build_publish_deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Build images
      run: docker-compose build
        
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
        
    - name: Tag and Push Docker images
      run: |
          docker tag final-ing-softw-3_back:latest ${{ secrets.DOCKERHUB_USERNAME }}/final-ing-softw-3-backend:latest
          docker tag final-ing-softw-3_front:latest ${{ secrets.DOCKERHUB_USERNAME }}/final-ing-softw-3-frontend:latest
          docker tag final-ing-softw-3_database:latest ${{ secrets.DOCKERHUB_USERNAME }}/final-ing-softw-3-database:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/final-ing-softw-3-frontend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/final-ing-softw-3-backend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/final-ing-softw-3-database:latest

    - name: Configurar auth Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v0.5.0
      with:
          service_account_key: ${{ secrets.GCLOUD_AUTH }}
          export_default_credentials: true
          project_id: diario-428220

    - name: Ensure Cloud SQL API is enabled
      run: gcloud services enable sqladmin.googleapis.com
    
    - name: Initiate Cloud SQL instance if not initiated
      run: |
            INSTANCE_NAME=diario
            PROJECT_ID=diario-428220
            REGION=us-central1
    
            if ! gcloud sql instances describe $INSTANCE_NAME --project=$PROJECT_ID; then
              echo "Instance $INSTANCE_NAME does not exist. Creating..."
              gcloud sql instances create $INSTANCE_NAME --project=$PROJECT_ID --region=$REGION --tier=db-f1-micro --database-version=MYSQL_5_7
              gcloud sql databases create diario --instance=$INSTANCE_NAME --project=$PROJECT_ID
              gcloud sql users set-password root --host=% --instance=$INSTANCE_NAME --password=root
            else
              echo "Instance $INSTANCE_NAME exists. Skipping creation."
            fi


    - name: Configure Docker for Container Registry
      run: gcloud auth configure-docker

    - name: Push Docker images to Google Cloud Container Registry
      run: |
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/final-ing-softw-3-backend:latest gcr.io/diario-428220/final-ing-softw-3-backend-gc
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/final-ing-softw-3-frontend:latest gcr.io/diario-428220/final-ing-softw-3-frontend-gc
          docker push gcr.io/diario-428220/final-ing-softw-3-backend-gc:latest
          docker push gcr.io/diario-428220/final-ing-softw-3-frontend-gc:latest

    - name: Import SQL file to Cloud SQL
      run: |
          gcloud --quiet sql import sql diario gs://bd_temp/db.sql

    - name: Deploy Frontend
      run: |
          gcloud run deploy frontend \
            --image=gcr.io/diario-428220/final-ing-softw-3-frontend-gc \
            --platform=managed \
            --region=us-central1 \
            --allow-unauthenticated \
            --port=3000 \
            --max-instances=15

    - name: Deploy Backend
      run: |
          gcloud run deploy backend \
           --image=gcr.io/diario-428220/final-ing-softw-3-backend-gc:latest \
           --port=8080 \
           --platform=managed \
           --region=us-central1 \
           --allow-unauthenticated \
           --max-instances=15 \
           --add-cloudsql-instances=diario \
           --set-env-vars=DB_HOST=104.154.18.138,DB_PORT=3306,DB_NAME=diario,DB_USER=root,DB_PASS=root \

