name: Build and Publish
on:
  push:
    branches:
      - main
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Build images
      run: docker-compose build
      
    - name: List Docker images
      run: docker images

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
        
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
        
    - name: Tag and Push Docker images
      run: |
          docker images
          docker tag final-ing-softw-3_back:latest ${{ secrets.DOCKERHUB_USERNAME }}/final-ing-softw-3-backend:latest
          docker tag final-ing-softw-3_front:latest ${{ secrets.DOCKERHUB_USERNAME }}/final-ing-softw-3-frontend:latest
          docker tag final-ing-softw-3_database:latest ${{ secrets.DOCKERHUB_USERNAME }}/final-ing-softw-3-database:latest
          docker images
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/final-ing-softw-3-backend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/final-ing-softw-3-frontend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/final-ing-softw-3-database:latest
          
    - name: Configurar auth Google Cloud CLI
      uses: google-github-actions/auth@v0.4.1
      with:
          service_account_key: ${{ secrets.GCLOUD_AUTH }}
          credentials_json: ${{ secrets.GCLOUD_AUTH }}
          project_id: diario-414100

    - name: Deploy Frontend
      run: |
          gcloud run deploy frontend \
            --image=gcr.io/diario-414100/gc-final-ing-softw-3-frontend \
            --platform=managed \
            --region=southamerica-east1 \
            --allow-unauthenticated
