name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Tag and push Docker images
      run: |
          docker tag integradoringsw3-backend:latest ${{ secrets.DOCKERHUB_USERNAME }}/integradoringsw3-backend:latest
          docker tag integradoringsw3-frontend:latest ${{ secrets.DOCKERHUB_USERNAME }}/integradoringsw3-frontend:latest
          docker tag integradoringsw3-database ${{ secrets.DOCKERHUB_USERNAME }}/integradoringsw3-database

          docker push ${{ secrets.DOCKERHUB_USERNAME }}/integradoringsw3-backend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/integradoringsw3-frontend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/integradoringsw3-database
